name: cirestechnologies

services:
  cirestechnologies-cache:
    image: 'redis:latest'
    container_name: cirestechnologies-cache
    hostname: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - cirestechnologies

  app:
    container_name: cirestechnologies
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    ports:
      - "9090:9090"
    depends_on:
      cirestechnologies-cache:
        condition: service_healthy
    restart: no
    networks:
      - cirestechnologies

networks:
  cirestechnologies:
    attachable: true
    name: cirestechnologies
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112


volumes:
  postgres-db:
    driver: local
